---
kind: pipeline
type: docker
name: default

steps:
- name: create-queue
  image: amazon/aws-cli
  when:
    branch:
    - develop
    - release/*
    - master
  commands:
  - aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name teste-drone
